version: "3.5"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/rthammat/data/mariadb
      o: bind
      type: none

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb_image
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always
